Feat/add managed accounts
casdoor/casdoor-chrome-extension pull request #10
Opened 2022-08-25 14:43 UTC by Resulte

https://user-images.githubusercontent.com/34178764/186695911-bb1cf00f-0430-4ea6-886d-d1ed981346f4.mov

2022-08-26 09:01 UTC, hsluoyz requested changes

2022-08-26 09:01 UTC, hsluoyz commented on manifest.json
> +                "https://*.casdoor.com/login/*",
What's this?

2022-08-26 09:01 UTC, hsluoyz commented on src/content-script.js
> +    usernameXpath,
Will this work for other sites?

2022-08-31 14:42 UTC, Resulte commented
https://user-images.githubusercontent.com/34178764/187706740-9b861651-1175-4e97-b075-c960368a0c35.mov

2022-09-01 05:10 UTC, hsluoyz approved these changes

2022-09-01 05:10 UTC, merged